version : '1'

services: 
  mongodb: 
    image: mongo:latest
    ports: 
      - '27017:27017'
    volumes: 
      - dbdata:/data/db
    networks: 
      - js-network

volumes:
  dbdata:

networks:
  js-network:
    driver: bridge